[package]
name = "learning-db"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
learning-assets = { path = "../learning-assets" }
learning-core = { path = "../learning-core" }
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tokio.workspace = true
chrono.workspace = true
