use sha2::{Digest, Sha256};
use std::{
    collections::HashSet,
    fs::{self, File, OpenOptions},
    io::{self, Read, Seek, SeekFrom, Write},
    path::{Path, PathBuf},
    time::SystemTime,
};
use thiserror::Error;
use uuid::Uuid;

const COPY_BUFFER_SIZE: usize = 64 * 1024;

#[derive(Debug, Error)]
pub enum AssetIoError {
    #[error("asset source aliases the staging area")]
    InvalidSource,
    #[error("asset file is missing: {0}")]
    Missing(String),
    #[error("asset file is corrupt: {0}")]
    Corrupt(String),
    #[error("asset byte count overflow")]
    SizeOverflow,
    #[error("declared upload size exceeds the trusted upload limit")]
    InvalidDeclaration,
    #[error("upload exceeds its declared size or trusted limit")]
    UploadLimitExceeded,
    #[error("upload byte count differs from its declaration")]
    DeclaredSizeMismatch,
    #[error("invalid asset metadata or reconciliation protection key")]
    InvalidMetadata,
    #[error(transparent)]
    Io(#[from] io::Error),
}

/// A byte object whose key, digest, and size were generated by this store.
/// Database authorization is a separate decision; callers cannot construct this token.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifiedBlob {
    storage_key: String,
    sha256: String,
    size_bytes: u64,
}

/// The trusted service supplies `max_size_bytes` from its upload policy, not
/// from the untrusted request. `expected_size_bytes` is the declared byte
/// count and must be confirmed while streaming before publication.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UploadDeclaration {
    pub expected_size_bytes: u64,
    pub max_size_bytes: u64,
}

/// A possible orphan reported by a read-only scan. `path` is a logical key,
/// never a caller-supplied filesystem path. Reporting does not authorize deletion.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReconcileCandidate {
    pub path: String,
    pub modified_at: SystemTime,
    pub size_bytes: u64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReconcileReport {
    pub candidates: Vec<ReconcileCandidate>,
}

impl VerifiedBlob {
    pub fn storage_key(&self) -> &str {
        &self.storage_key
    }

    pub fn sha256(&self) -> &str {
        &self.sha256
    }

    pub fn size_bytes(&self) -> u64 {
        self.size_bytes
    }
}

#[derive(Debug, Clone)]
pub struct FsAssetStore {
    assets_root: PathBuf,
    staging_root: PathBuf,
}

impl FsAssetStore {
    /// Called only after the database has authorized the exact asset use.
    /// Rehashes both the stored file and the bytes copied to the package.
    pub(crate) fn copy_verified(
        &self,
        storage_key: &str,
        sha256: &str,
        size: u64,
        target: &mut File,
    ) -> Result<(), AssetIoError> {
        let declared = i64::try_from(size).map_err(|_| AssetIoError::InvalidMetadata)?;
        let mut source = self.open_record(storage_key, sha256, declared)?;
        let (copied_hash, copied_size) = copy_and_hash(
            &mut source,
            target,
            UploadDeclaration {
                expected_size_bytes: size,
                max_size_bytes: size,
            },
        )?;
        if copied_hash != sha256 || copied_size != size {
            return Err(AssetIoError::Corrupt(storage_key.into()));
        }
        Ok(())
    }
    pub fn new(assets_root: PathBuf, staging_root: PathBuf) -> Result<Self, AssetIoError> {
        fs::create_dir_all(&assets_root)?;
        fs::create_dir_all(&staging_root)?;
        Ok(Self {
            assets_root,
            staging_root,
        })
    }

    /// Stage original bytes before publishing an immutable digest object.
    /// Incomplete staging and finalization files are retained on failure for reconciliation.
    pub fn put_from_file(
        &self,
        upload_id: Uuid,
        source: &Path,
        declaration: UploadDeclaration,
    ) -> Result<VerifiedBlob, AssetIoError> {
        // A source inside staging is an incomplete upload, not a trusted source.
        // This also rejects a symlink to the named staging path before any write.
        if source
            .canonicalize()?
            .starts_with(self.staging_root.canonicalize()?)
        {
            return Err(AssetIoError::InvalidSource);
        }
        let mut input = File::open(source)?;
        self.put_from_reader(upload_id, &mut input, declaration)
    }

    fn put_from_reader(
        &self,
        upload_id: Uuid,
        input: &mut impl Read,
        declaration: UploadDeclaration,
    ) -> Result<VerifiedBlob, AssetIoError> {
        self.put_from_reader_with_stage_hook(upload_id, input, declaration, |_| {})
    }

    // A private seam lets the unit test alter the named stage at the exact
    // boundary between the two volume writes, without a timing race.
    fn put_from_reader_with_stage_hook(
        &self,
        upload_id: Uuid,
        input: &mut impl Read,
        declaration: UploadDeclaration,
        before_second_copy: impl FnOnce(&Path),
    ) -> Result<VerifiedBlob, AssetIoError> {
        if declaration.expected_size_bytes > declaration.max_size_bytes {
            return Err(AssetIoError::InvalidDeclaration);
        }
        let stage_path = self.staging_root.join(upload_id.to_string());
        // A unique incoming file avoids truncating the source even if it is a
        // hard-link alias of an interrupted named stage outside this directory.
        let incoming_path = self
            .staging_root
            .join(format!("{upload_id}.incoming-{}", Uuid::new_v4()));
        let mut stage = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&incoming_path)?;
        let (sha256, size_bytes) = copy_and_hash(input, &mut stage, declaration)?;
        stage.sync_all()?;
        sync_directory(&self.staging_root)?;
        drop(stage);
        if stage_path.exists() {
            fs::remove_file(&stage_path)?;
        }
        fs::rename(&incoming_path, &stage_path)?;
        sync_directory(&self.staging_root)?;
        before_second_copy(&stage_path);

        let storage_key = format!("sha256/{}/{}", &sha256[..2], sha256);
        let blob = VerifiedBlob {
            storage_key,
            sha256,
            size_bytes,
        };
        let digest_root = ensure_child_directory(&self.assets_root, "sha256")?;
        let final_dir = ensure_child_directory(&digest_root, &blob.sha256[..2])?;
        let final_path = final_dir.join(&blob.sha256);

        if final_path.exists() {
            self.verify(&blob)?;
            sync_directory(&final_dir)?;
            fs::remove_file(stage_path)?;
            return Ok(blob);
        }

        // The staging and assets roots can be distinct volumes. Copy and sync on
        // the assets volume before the final name becomes visible.
        let finalizing_dir = ensure_child_directory(&self.assets_root, ".finalizing")?;
        let pending_path = finalizing_dir.join(format!("{upload_id}.pending-{}", Uuid::new_v4()));
        let mut pending = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&pending_path)?;
        let mut staged = File::open(&stage_path)?;
        let (copied_sha256, copied_size) = copy_and_hash(&mut staged, &mut pending, declaration)?;
        drop(staged);
        pending.sync_all()?;
        drop(pending);
        if copied_sha256 != blob.sha256 || copied_size != blob.size_bytes {
            return Err(AssetIoError::Corrupt(stage_path.display().to_string()));
        }
        sync_directory(&finalizing_dir)?;

        // hard_link is an atomic create-if-absent on this volume. Unlike portable
        // rename, it never clobbers a concurrent writer's digest target.
        match fs::hard_link(&pending_path, &final_path) {
            Ok(()) => {}
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {
                self.verify(&blob)?;
            }
            Err(error) => return Err(error.into()),
        }
        self.verify(&blob)?;
        sync_directory(&final_dir)?;
        fs::remove_file(pending_path)?;
        sync_directory(&finalizing_dir)?;
        fs::remove_file(stage_path)?;
        Ok(blob)
    }

    pub fn verify(&self, blob: &VerifiedBlob) -> Result<(), AssetIoError> {
        let mut file = self.open_checked(blob)?;
        verify_file(&mut file, blob)
    }

    /// Rehash the opened file handle, then rewind it for the caller.
    pub fn open(&self, blob: &VerifiedBlob) -> Result<File, AssetIoError> {
        let mut file = self.open_checked(blob)?;
        verify_file(&mut file, blob)?;
        file.seek(SeekFrom::Start(0))?;
        Ok(file)
    }

    /// Trusted storage-adapter entry point for database metadata. Application
    /// access must go through `AssetStore::open_for_use`, which checks the exact
    /// current use before calling this method. Reconstruct the private token
    /// only from a canonical digest key and rehash the opened file.
    pub fn open_record(
        &self,
        storage_key: &str,
        sha256: &str,
        byte_size: i64,
    ) -> Result<File, AssetIoError> {
        if sha256.len() != 64
            || !sha256
                .bytes()
                .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
            || storage_key != format!("sha256/{}/{}", &sha256[..2], sha256)
        {
            return Err(AssetIoError::InvalidMetadata);
        }
        let size_bytes = u64::try_from(byte_size).map_err(|_| AssetIoError::InvalidMetadata)?;
        self.open(&VerifiedBlob {
            storage_key: storage_key.into(),
            sha256: sha256.into(),
            size_bytes,
        })
    }

    /// Dry-run only. `protected` must contain every referenced/backup digest
    /// key and every active upload UUID (or exact staging/pending key). While
    /// any upload is active, all digest candidates are withheld: the digest
    /// path no longer identifies its upload after finalization. This deliberate
    /// false negative avoids proposing active bytes. No file is deleted, and
    /// unfamiliar names are not proposed for deletion.
    pub fn reconcile(
        &self,
        protected: &HashSet<String>,
        older_than: SystemTime,
    ) -> Result<ReconcileReport, AssetIoError> {
        if !protected.iter().all(|key| valid_protection_key(key)) {
            return Err(AssetIoError::InvalidMetadata);
        }
        require_real_directory(&self.assets_root)?;
        require_real_directory(&self.staging_root)?;
        let active_uploads: HashSet<Uuid> = protected
            .iter()
            .filter_map(|key| protected_upload_id(key))
            .collect();
        let mut candidates = Vec::new();
        if active_uploads.is_empty() {
            let digest_root = self.assets_root.join("sha256");
            for prefix_dir in read_real_directory(&digest_root)? {
                let name = prefix_dir.file_name();
                let Some(prefix) = name.to_str() else {
                    continue;
                };
                if prefix.len() != 2
                    || !prefix
                        .bytes()
                        .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
                {
                    continue;
                }
                if !prefix_dir.file_type()?.is_dir() {
                    continue;
                }
                for entry in read_real_directory(&prefix_dir.path())? {
                    let Some(digest) = entry.file_name().to_str().map(str::to_owned) else {
                        continue;
                    };
                    let key = format!("sha256/{prefix}/{digest}");
                    if valid_digest_key(&key) {
                        consider(
                            &entry,
                            key,
                            None,
                            protected,
                            &active_uploads,
                            older_than,
                            &mut candidates,
                        )?;
                    }
                }
            }
        }
        for entry in read_real_directory(&self.staging_root)? {
            let Some(name) = entry.file_name().to_str().map(str::to_owned) else {
                continue;
            };
            if let Some(upload) = stage_upload_id(&name) {
                consider(
                    &entry,
                    format!("staging/{name}"),
                    Some(upload),
                    protected,
                    &active_uploads,
                    older_than,
                    &mut candidates,
                )?;
            }
        }
        for entry in read_real_directory(&self.assets_root.join(".finalizing"))? {
            let Some(name) = entry.file_name().to_str().map(str::to_owned) else {
                continue;
            };
            if let Some(upload) = pending_upload_id(&name) {
                consider(
                    &entry,
                    format!(".finalizing/{name}"),
                    Some(upload),
                    protected,
                    &active_uploads,
                    older_than,
                    &mut candidates,
                )?;
            }
        }
        candidates.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(ReconcileReport { candidates })
    }

    fn open_checked(&self, blob: &VerifiedBlob) -> Result<File, AssetIoError> {
        let digest_root = self.assets_root.join("sha256");
        let prefix_root = digest_root.join(&blob.sha256[..2]);
        for directory in [&digest_root, &prefix_root] {
            match fs::symlink_metadata(directory) {
                Ok(metadata) if metadata.file_type().is_dir() => {}
                Ok(_) => return Err(AssetIoError::Corrupt(blob.storage_key.clone())),
                Err(error) if error.kind() == io::ErrorKind::NotFound => {
                    return Err(AssetIoError::Missing(blob.storage_key.clone()));
                }
                Err(error) => return Err(error.into()),
            }
        }
        let path = self.assets_root.join(&blob.storage_key);
        match fs::symlink_metadata(&path) {
            Ok(metadata) if metadata.file_type().is_file() => {}
            Ok(_) => return Err(AssetIoError::Corrupt(blob.storage_key.clone())),
            Err(error) if error.kind() == io::ErrorKind::NotFound => {
                return Err(AssetIoError::Missing(blob.storage_key.clone()));
            }
            Err(error) => return Err(error.into()),
        }
        File::open(&path).map_err(|error| {
            if error.kind() == io::ErrorKind::NotFound {
                AssetIoError::Missing(blob.storage_key.clone())
            } else {
                error.into()
            }
        })
    }
}

fn canonical_uuid(text: &str) -> Option<Uuid> {
    let id = Uuid::parse_str(text).ok()?;
    (id.to_string() == text).then_some(id)
}

fn stage_upload_id(name: &str) -> Option<Uuid> {
    if let Some((upload, incoming)) = name.split_once(".incoming-") {
        canonical_uuid(incoming)?;
        canonical_uuid(upload)
    } else {
        canonical_uuid(name)
    }
}

fn pending_upload_id(name: &str) -> Option<Uuid> {
    let (upload, pending) = name.split_once(".pending-")?;
    canonical_uuid(pending)?;
    canonical_uuid(upload)
}

fn valid_digest_key(key: &str) -> bool {
    let mut parts = key.split('/');
    let (Some("sha256"), Some(prefix), Some(digest), None) =
        (parts.next(), parts.next(), parts.next(), parts.next())
    else {
        return false;
    };
    digest.len() == 64
        && digest
            .bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
        && prefix == &digest[..2]
}

fn valid_protection_key(key: &str) -> bool {
    valid_digest_key(key) || protected_upload_id(key).is_some()
}

fn protected_upload_id(key: &str) -> Option<Uuid> {
    canonical_uuid(key)
        .or_else(|| key.strip_prefix("staging/").and_then(stage_upload_id))
        .or_else(|| key.strip_prefix(".finalizing/").and_then(pending_upload_id))
}

fn read_real_directory(path: &Path) -> Result<Vec<fs::DirEntry>, AssetIoError> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(vec![]),
        Err(error) => return Err(error.into()),
    };
    if !metadata.file_type().is_dir() {
        return Err(AssetIoError::Corrupt(path.display().to_string()));
    }
    fs::read_dir(path)?
        .collect::<Result<Vec<_>, _>>()
        .map_err(Into::into)
}

fn require_real_directory(path: &Path) -> Result<(), AssetIoError> {
    let metadata = fs::symlink_metadata(path)?;
    if !metadata.file_type().is_dir() {
        return Err(AssetIoError::Corrupt(path.display().to_string()));
    }
    Ok(())
}

fn consider(
    entry: &fs::DirEntry,
    path: String,
    upload: Option<Uuid>,
    protected: &HashSet<String>,
    active_uploads: &HashSet<Uuid>,
    older_than: SystemTime,
    candidates: &mut Vec<ReconcileCandidate>,
) -> Result<(), AssetIoError> {
    if protected.contains(&path) || upload.is_some_and(|id| active_uploads.contains(&id)) {
        return Ok(());
    }
    let metadata = fs::symlink_metadata(entry.path())?;
    if metadata.file_type().is_file() && metadata.modified()? < older_than {
        candidates.push(ReconcileCandidate {
            path,
            modified_at: metadata.modified()?,
            size_bytes: metadata.len(),
        });
    }
    Ok(())
}

fn copy_and_hash(
    source: &mut impl Read,
    destination: &mut impl Write,
    declaration: UploadDeclaration,
) -> Result<(String, u64), AssetIoError> {
    let mut hasher = Sha256::new();
    let mut size_bytes = 0_u64;
    let mut buffer = [0_u8; COPY_BUFFER_SIZE];
    loop {
        let read = source.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        let next_size = size_bytes
            .checked_add(read as u64)
            .ok_or(AssetIoError::SizeOverflow)?;
        if next_size > declaration.max_size_bytes || next_size > declaration.expected_size_bytes {
            return Err(AssetIoError::UploadLimitExceeded);
        }
        destination.write_all(&buffer[..read])?;
        hasher.update(&buffer[..read]);
        size_bytes = next_size;
    }
    if size_bytes != declaration.expected_size_bytes {
        return Err(AssetIoError::DeclaredSizeMismatch);
    }
    Ok((format!("{:x}", hasher.finalize()), size_bytes))
}

fn verify_file(file: &mut File, blob: &VerifiedBlob) -> Result<(), AssetIoError> {
    if file.metadata()?.len() != blob.size_bytes {
        return Err(AssetIoError::Corrupt(blob.storage_key.clone()));
    }
    let mut hasher = Sha256::new();
    let mut size_bytes = 0_u64;
    let mut buffer = [0_u8; COPY_BUFFER_SIZE];
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
        size_bytes = size_bytes
            .checked_add(read as u64)
            .ok_or(AssetIoError::SizeOverflow)?;
    }
    if size_bytes != blob.size_bytes || format!("{:x}", hasher.finalize()) != blob.sha256 {
        return Err(AssetIoError::Corrupt(blob.storage_key.clone()));
    }
    Ok(())
}

fn ensure_child_directory(parent: &Path, name: &str) -> Result<PathBuf, AssetIoError> {
    let child = parent.join(name);
    match fs::create_dir(&child) {
        Ok(()) => {}
        Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {
            if !fs::symlink_metadata(&child)?.file_type().is_dir() {
                return Err(AssetIoError::Corrupt(child.display().to_string()));
            }
        }
        Err(error) => return Err(error.into()),
    }
    // A retry must also flush a directory name created by a prior attempt
    // that crashed between create_dir and its parent-directory sync.
    sync_directory(parent)?;
    Ok(child)
}

#[cfg(unix)]
fn sync_directory(path: &Path) -> Result<(), AssetIoError> {
    File::open(path)?.sync_all()?;
    Ok(())
}

#[cfg(not(unix))]
fn sync_directory(_path: &Path) -> Result<(), AssetIoError> {
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestRoot(PathBuf);

    impl TestRoot {
        fn new() -> Self {
            let root =
                std::env::temp_dir().join(format!("learning-assets-fault-{}", Uuid::new_v4()));
            fs::create_dir(&root).unwrap();
            Self(root)
        }
    }

    impl Drop for TestRoot {
        fn drop(&mut self) {
            fs::remove_dir_all(&self.0).unwrap();
        }
    }

    struct FailAfterFirstChunk(bool);

    impl Read for FailAfterFirstChunk {
        fn read(&mut self, buffer: &mut [u8]) -> io::Result<usize> {
            if self.0 {
                return Err(io::Error::other("injected read interruption"));
            }
            self.0 = true;
            buffer[..5].copy_from_slice(b"start");
            Ok(5)
        }
    }

    #[test]
    fn interrupted_stream_keeps_unpublished_partial_stage() {
        let root = TestRoot::new();
        let assets = root.0.join("assets");
        let staging = root.0.join("staging");
        let store = FsAssetStore::new(assets.clone(), staging.clone()).unwrap();
        let upload_id = Uuid::new_v4();

        assert!(
            store
                .put_from_reader(
                    upload_id,
                    &mut FailAfterFirstChunk(false),
                    UploadDeclaration {
                        expected_size_bytes: 10,
                        max_size_bytes: 10,
                    },
                )
                .is_err()
        );
        let partials: Vec<_> = fs::read_dir(&staging)
            .unwrap()
            .collect::<Result<_, _>>()
            .unwrap();
        assert_eq!(partials.len(), 1);
        assert!(
            partials[0]
                .file_name()
                .to_string_lossy()
                .starts_with(&format!("{upload_id}.incoming-"))
        );
        assert_eq!(fs::read(partials[0].path()).unwrap(), b"start");
        assert!(!assets.join("sha256").exists());
    }

    #[test]
    fn second_volume_copy_does_not_write_past_the_declared_limit() {
        let root = TestRoot::new();
        let assets = root.0.join("assets");
        let staging = root.0.join("staging");
        let store = FsAssetStore::new(assets.clone(), staging).unwrap();
        let original = vec![b'a'; 100_000];
        let digest = format!("{:x}", Sha256::digest(&original));
        let mut input = io::Cursor::new(original);
        let declaration = UploadDeclaration {
            expected_size_bytes: 100_000,
            max_size_bytes: 100_000,
        };

        let result = store.put_from_reader_with_stage_hook(
            Uuid::new_v4(),
            &mut input,
            declaration,
            |named_stage| {
                let mut stage = OpenOptions::new().append(true).open(named_stage).unwrap();
                stage.write_all(&vec![b'b'; 100_000]).unwrap();
                stage.sync_all().unwrap();
            },
        );
        assert!(
            matches!(&result, Err(AssetIoError::UploadLimitExceeded)),
            "the second copy must stop at the upload limit: {result:?}"
        );
        let pending: Vec<_> = fs::read_dir(assets.join(".finalizing"))
            .unwrap()
            .map(|entry| entry.unwrap())
            .collect();
        assert_eq!(pending.len(), 1, "failed copy stays reconcilable");
        assert!(
            pending[0].metadata().unwrap().len() <= declaration.max_size_bytes,
            "the assets volume must never receive bytes beyond the upload limit"
        );
        assert!(
            !assets
                .join("sha256")
                .join(&digest[..2])
                .join(digest)
                .exists(),
            "a failed second copy must not publish a digest object"
        );
    }
}
