use sha2::{Digest, Sha256};
use std::{
    fs::{self, File, OpenOptions},
    io::{self, Read, Seek, SeekFrom, Write},
    path::{Path, PathBuf},
};
use thiserror::Error;
use uuid::Uuid;

const COPY_BUFFER_SIZE: usize = 64 * 1024;

#[derive(Debug, Error)]
pub enum AssetIoError {
    #[error("asset source aliases the staging area")]
    InvalidSource,
    #[error("asset file is missing: {0}")]
    Missing(String),
    #[error("asset file is corrupt: {0}")]
    Corrupt(String),
    #[error("asset byte count overflow")]
    SizeOverflow,
    #[error(transparent)]
    Io(#[from] io::Error),
}

/// A byte object whose key, digest, and size were generated by this store.
/// Database authorization is a separate decision; callers cannot construct this token.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifiedBlob {
    storage_key: String,
    sha256: String,
    size_bytes: u64,
}

impl VerifiedBlob {
    pub fn storage_key(&self) -> &str {
        &self.storage_key
    }

    pub fn sha256(&self) -> &str {
        &self.sha256
    }

    pub fn size_bytes(&self) -> u64 {
        self.size_bytes
    }
}

#[derive(Debug, Clone)]
pub struct FsAssetStore {
    assets_root: PathBuf,
    staging_root: PathBuf,
}

impl FsAssetStore {
    pub fn new(assets_root: PathBuf, staging_root: PathBuf) -> Result<Self, AssetIoError> {
        fs::create_dir_all(&assets_root)?;
        fs::create_dir_all(&staging_root)?;
        Ok(Self {
            assets_root,
            staging_root,
        })
    }

    /// Stage original bytes before publishing an immutable digest object.
    /// Incomplete staging and finalization files are retained on failure for reconciliation.
    pub fn put_from_file(
        &self,
        upload_id: Uuid,
        source: &Path,
    ) -> Result<VerifiedBlob, AssetIoError> {
        // A source inside staging is an incomplete upload, not a trusted source.
        // This also rejects a symlink to the named staging path before any write.
        if source
            .canonicalize()?
            .starts_with(self.staging_root.canonicalize()?)
        {
            return Err(AssetIoError::InvalidSource);
        }
        let mut input = File::open(source)?;
        self.put_from_reader(upload_id, &mut input)
    }

    fn put_from_reader(
        &self,
        upload_id: Uuid,
        input: &mut impl Read,
    ) -> Result<VerifiedBlob, AssetIoError> {
        let stage_path = self.staging_root.join(upload_id.to_string());
        // A unique incoming file avoids truncating the source even if it is a
        // hard-link alias of an interrupted named stage outside this directory.
        let incoming_path = self
            .staging_root
            .join(format!("{upload_id}.incoming-{}", Uuid::new_v4()));
        let mut stage = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&incoming_path)?;
        let (sha256, size_bytes) = copy_and_hash(input, &mut stage)?;
        stage.sync_all()?;
        sync_directory(&self.staging_root)?;
        drop(stage);
        if stage_path.exists() {
            fs::remove_file(&stage_path)?;
        }
        fs::rename(&incoming_path, &stage_path)?;
        sync_directory(&self.staging_root)?;

        let storage_key = format!("sha256/{}/{}", &sha256[..2], sha256);
        let blob = VerifiedBlob {
            storage_key,
            sha256,
            size_bytes,
        };
        let digest_root = ensure_child_directory(&self.assets_root, "sha256")?;
        let final_dir = ensure_child_directory(&digest_root, &blob.sha256[..2])?;
        let final_path = final_dir.join(&blob.sha256);

        if final_path.exists() {
            self.verify(&blob)?;
            sync_directory(&final_dir)?;
            fs::remove_file(stage_path)?;
            return Ok(blob);
        }

        // The staging and assets roots can be distinct volumes. Copy and sync on
        // the assets volume before the final name becomes visible.
        let finalizing_dir = ensure_child_directory(&self.assets_root, ".finalizing")?;
        let pending_path = finalizing_dir.join(format!("{upload_id}.pending-{}", Uuid::new_v4()));
        let mut pending = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&pending_path)?;
        let mut staged = File::open(&stage_path)?;
        let (copied_sha256, copied_size) = copy_and_hash(&mut staged, &mut pending)?;
        drop(staged);
        pending.sync_all()?;
        drop(pending);
        if copied_sha256 != blob.sha256 || copied_size != blob.size_bytes {
            return Err(AssetIoError::Corrupt(stage_path.display().to_string()));
        }
        sync_directory(&finalizing_dir)?;

        // hard_link is an atomic create-if-absent on this volume. Unlike portable
        // rename, it never clobbers a concurrent writer's digest target.
        match fs::hard_link(&pending_path, &final_path) {
            Ok(()) => {}
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {
                self.verify(&blob)?;
            }
            Err(error) => return Err(error.into()),
        }
        self.verify(&blob)?;
        sync_directory(&final_dir)?;
        fs::remove_file(pending_path)?;
        sync_directory(&finalizing_dir)?;
        fs::remove_file(stage_path)?;
        Ok(blob)
    }

    pub fn verify(&self, blob: &VerifiedBlob) -> Result<(), AssetIoError> {
        let mut file = self.open_checked(blob)?;
        verify_file(&mut file, blob)
    }

    /// Rehash the opened file handle, then rewind it for the caller.
    pub fn open(&self, blob: &VerifiedBlob) -> Result<File, AssetIoError> {
        let mut file = self.open_checked(blob)?;
        verify_file(&mut file, blob)?;
        file.seek(SeekFrom::Start(0))?;
        Ok(file)
    }

    fn open_checked(&self, blob: &VerifiedBlob) -> Result<File, AssetIoError> {
        let path = self.assets_root.join(&blob.storage_key);
        match fs::symlink_metadata(&path) {
            Ok(metadata) if metadata.file_type().is_file() => {}
            Ok(_) => return Err(AssetIoError::Corrupt(blob.storage_key.clone())),
            Err(error) if error.kind() == io::ErrorKind::NotFound => {
                return Err(AssetIoError::Missing(blob.storage_key.clone()));
            }
            Err(error) => return Err(error.into()),
        }
        File::open(&path).map_err(|error| {
            if error.kind() == io::ErrorKind::NotFound {
                AssetIoError::Missing(blob.storage_key.clone())
            } else {
                error.into()
            }
        })
    }
}

fn copy_and_hash(
    source: &mut impl Read,
    destination: &mut impl Write,
) -> Result<(String, u64), AssetIoError> {
    let mut hasher = Sha256::new();
    let mut size_bytes = 0_u64;
    let mut buffer = [0_u8; COPY_BUFFER_SIZE];
    loop {
        let read = source.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        destination.write_all(&buffer[..read])?;
        hasher.update(&buffer[..read]);
        size_bytes = size_bytes
            .checked_add(read as u64)
            .ok_or(AssetIoError::SizeOverflow)?;
    }
    Ok((format!("{:x}", hasher.finalize()), size_bytes))
}

fn verify_file(file: &mut File, blob: &VerifiedBlob) -> Result<(), AssetIoError> {
    if file.metadata()?.len() != blob.size_bytes {
        return Err(AssetIoError::Corrupt(blob.storage_key.clone()));
    }
    let mut hasher = Sha256::new();
    let mut size_bytes = 0_u64;
    let mut buffer = [0_u8; COPY_BUFFER_SIZE];
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
        size_bytes = size_bytes
            .checked_add(read as u64)
            .ok_or(AssetIoError::SizeOverflow)?;
    }
    if size_bytes != blob.size_bytes || format!("{:x}", hasher.finalize()) != blob.sha256 {
        return Err(AssetIoError::Corrupt(blob.storage_key.clone()));
    }
    Ok(())
}

fn ensure_child_directory(parent: &Path, name: &str) -> Result<PathBuf, AssetIoError> {
    let child = parent.join(name);
    match fs::create_dir(&child) {
        Ok(()) => {}
        Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {
            if !fs::symlink_metadata(&child)?.file_type().is_dir() {
                return Err(AssetIoError::Corrupt(child.display().to_string()));
            }
        }
        Err(error) => return Err(error.into()),
    }
    // A retry must also flush a directory name created by a prior attempt
    // that crashed between create_dir and its parent-directory sync.
    sync_directory(parent)?;
    Ok(child)
}

#[cfg(unix)]
fn sync_directory(path: &Path) -> Result<(), AssetIoError> {
    File::open(path)?.sync_all()?;
    Ok(())
}

#[cfg(not(unix))]
fn sync_directory(_path: &Path) -> Result<(), AssetIoError> {
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestRoot(PathBuf);

    impl TestRoot {
        fn new() -> Self {
            let root =
                std::env::temp_dir().join(format!("learning-assets-fault-{}", Uuid::new_v4()));
            fs::create_dir(&root).unwrap();
            Self(root)
        }
    }

    impl Drop for TestRoot {
        fn drop(&mut self) {
            fs::remove_dir_all(&self.0).unwrap();
        }
    }

    struct FailAfterFirstChunk(bool);

    impl Read for FailAfterFirstChunk {
        fn read(&mut self, buffer: &mut [u8]) -> io::Result<usize> {
            if self.0 {
                return Err(io::Error::other("injected read interruption"));
            }
            self.0 = true;
            buffer[..5].copy_from_slice(b"start");
            Ok(5)
        }
    }

    #[test]
    fn interrupted_stream_keeps_unpublished_partial_stage() {
        let root = TestRoot::new();
        let assets = root.0.join("assets");
        let staging = root.0.join("staging");
        let store = FsAssetStore::new(assets.clone(), staging.clone()).unwrap();
        let upload_id = Uuid::new_v4();

        assert!(
            store
                .put_from_reader(upload_id, &mut FailAfterFirstChunk(false))
                .is_err()
        );
        let partials: Vec<_> = fs::read_dir(&staging)
            .unwrap()
            .collect::<Result<_, _>>()
            .unwrap();
        assert_eq!(partials.len(), 1);
        assert!(
            partials[0]
                .file_name()
                .to_string_lossy()
                .starts_with(&format!("{upload_id}.incoming-"))
        );
        assert_eq!(fs::read(partials[0].path()).unwrap(), b"start");
        assert!(!assets.join("sha256").exists());
    }
}
